### ISSUE TITLE
Restructure repo for Google Fonts

### ISSUE THREAD

**Issue by justinpenner** [justinpenner/player-sans-mono#1]
I'm preparing this repo for submission to Google Fonts (see [`gf-structure`](https://github.com/justinpenner/player-sans-mono/tree/gf-structure) branch).

## TODO

- [x] Set up `config.yaml`
- [x] Update license file to GF format
- [ ] Add `meta` patch to `make build`
- [ ] Add `fix-italic-angle.py` patch to `make build`
- [ ] Update `.gitignore` to ignore `venv` and `fontbm` folders, and anything else that is generated/added after cloning the repo.

## Extras

- [ ] Include bitmap fonts in the repo (built by fontbm)
- [x] Write build script for building bitmap fonts
- [ ] Add bitmap font build instructions to readme
- [x] Python script for subsetting to only include 8x8 glyphs (still supports English and many African languages, but most European languages require the 8x13 version).
